/**
 * WebXray - Accessibility (a11y) Rule Catalog
 * Single source of truth for web accessibility audits mapped to WCAG 2.1 standards.
 * Category weights sum to 100.
 */

export const ACCESSIBILITY_RULES = [
  {
    id: 'a11y-form-labels',
    category: 'accessibility',
    title: 'Interactive form inputs have associated accessible labels',
    description: 'Ensures <input>, <select>, and <textarea> elements have a programmatic label.',
    weight: 18,
    severityOnFail: 'critical',
    whyItMatters: 'Unlabeled form controls prevent screen reader users from identifying what information to enter, creating major accessibility barriers.',
    recommendation: 'Associate each control with a <label for="id">, wrap it within a <label>, or provide an aria-label.',
    threshold: { maxUnlabeled: 0 },
    source: 'standard',
    reference: 'WCAG 1.3.1 Info and Relationships, 4.1.2 Name, Role, Value (Level A)',
  },
  {
    id: 'a11y-buttons-name',
    category: 'accessibility',
    title: 'Button elements have programmatic accessible names',
    description: 'Ensures all button elements provide visible text or an aria-label.',
    weight: 16,
    severityOnFail: 'critical',
    whyItMatters: 'Assistive technologies announce empty buttons as simply "button", leaving users unable to know what action will occur.',
    recommendation: 'Add visible text, an aria-label, or an svg with <title> inside the button.',
    threshold: { maxEmpty: 0 },
    source: 'standard',
    reference: 'WCAG 4.1.2 Name, Role, Value (Level A)',
  },
  {
    id: 'a11y-images-alt',
    category: 'accessibility',
    title: 'Images provide alternative text via alt attributes',
    description: 'Checks that <img> elements include an alt attribute describing image contents.',
    weight: 15,
    severityOnFail: 'high',
    whyItMatters: 'Screen readers cannot describe images without alt text, often reading raw filenames or skipping them altogether.',
    recommendation: 'Add meaningful alt attributes describing informative images, or alt="" for purely decorative graphics.',
    threshold: { maxMissing: 0 },
    source: 'standard',
    reference: 'WCAG 1.1.1 Non-text Content (Level A)',
  },
  {
    id: 'a11y-links-name',
    category: 'accessibility',
    title: 'Anchor links provide discernible text or accessible labels',
    description: 'Ensures hyperlinks communicate their target destination or action.',
    weight: 12,
    severityOnFail: 'high',
    whyItMatters: 'Empty links provide no context to screen reader users browsing through a page link list.',
    recommendation: 'Include descriptive text or an aria-label on every <a> element.',
    threshold: { maxEmpty: 0 },
    source: 'standard',
    reference: 'WCAG 2.4.4 Link Purpose (In Context, Level A), 4.1.2 Name, Role, Value',
  },
  {
    id: 'a11y-aria-hidden-focusable',
    category: 'accessibility',
    title: 'Focusable interactive elements are not obscured by aria-hidden',
    description: 'Prevents interactive controls with keyboard focus from being hidden from screen readers.',
    weight: 10,
    severityOnFail: 'high',
    whyItMatters: 'Keyboard users can navigate focus to these elements, but screen readers will be completely silent, causing confusing focus traps.',
    recommendation: 'Remove aria-hidden="true" or add tabindex="-1" to remove the element from the keyboard tab sequence.',
    threshold: { maxHidden: 0 },
    source: 'standard',
    reference: 'WAI-ARIA 1.2 / WCAG 4.1.2 Name, Role, Value',
  },
  {
    id: 'a11y-main-landmark',
    category: 'accessibility',
    title: 'Document includes a primary <main> content landmark',
    description: 'Verifies the presence of a <main> element or role="main" landmark container.',
    weight: 8,
    severityOnFail: 'medium',
    whyItMatters: 'The main landmark allows assistive technology users to skip repeated navigation links and jump directly to core content.',
    recommendation: 'Enclose the primary page content inside a <main> tag.',
    threshold: { minCount: 1 },
    source: 'standard',
    reference: 'WCAG 1.3.1 Info and Relationships, 2.4.1 Bypass Blocks (Level A)',
  },
  {
    id: 'a11y-duplicate-ids',
    category: 'accessibility',
    title: 'HTML id attributes are strictly unique within the DOM',
    description: 'Flags duplicate element IDs that break label associations and fragment navigation.',
    weight: 7,
    severityOnFail: 'medium',
    whyItMatters: 'Duplicate IDs cause assistive technologies and <label for="..."> associations to fail or behave unpredictably.',
    recommendation: 'Ensure all id attributes on the page are unique.',
    threshold: { maxDuplicates: 0 },
    source: 'standard',
    reference: 'WCAG 4.1.1 Parsing (Level A)',
  },
  {
    id: 'a11y-positive-tabindex',
    category: 'accessibility',
    title: 'Avoid positive tabindex values to preserve natural tab order',
    description: 'Checks that elements do not specify tabindex greater than 0.',
    weight: 6,
    severityOnFail: 'medium',
    whyItMatters: 'Positive tabindex values disrupt the natural DOM tab navigation order, confusing keyboard-only users.',
    recommendation: 'Remove positive tabindex values and rely on logical DOM source order or tabindex="0".',
    threshold: { maxPositive: 0 },
    source: 'standard',
    reference: 'WCAG 2.4.3 Focus Order (Level A)',
  },
  {
    id: 'a11y-html-lang',
    category: 'accessibility',
    title: 'HTML root element declares valid lang attribute',
    description: 'Ensures screen readers synthesize speech with appropriate language accents.',
    weight: 4,
    severityOnFail: 'medium',
    whyItMatters: 'Screen readers need a declared language to pronounce text with the correct phonetics and accent rules.',
    recommendation: 'Add a lang attribute to the <html> tag (e.g. <html lang="en">).',
    source: 'standard',
    reference: 'WCAG 3.1.1 Language of Page (Level A)',
  },
  {
    id: 'a11y-heading-skips',
    category: 'accessibility',
    title: 'Heading structure preserves logical hierarchical order',
    description: 'Validates that heading levels do not jump without intervening subheadings.',
    weight: 2,
    severityOnFail: 'medium',
    whyItMatters: 'Screen reader users rely on headings for navigation. Skipping levels causes confusion about document structure.',
    recommendation: 'Organize headings sequentially (H1 → H2 → H3).',
    threshold: { maxSkips: 0 },
    source: 'heuristic',
    reference: 'W3C Web Accessibility Tutorials: Headings',
  },
  {
    id: 'a11y-unknown-roles',
    category: 'accessibility',
    title: 'All ARIA roles conform to valid WAI-ARIA specifications',
    description: 'Detects unrecognized or misspelled ARIA role values on DOM elements.',
    weight: 2,
    severityOnFail: 'medium',
    whyItMatters: 'Browsers ignore invalid ARIA roles, falling back to default semantic behavior.',
    recommendation: 'Use valid WAI-ARIA role keywords.',
    threshold: { maxInvalid: 0 },
    source: 'standard',
    reference: 'WAI-ARIA 1.2 Specification',
  },
];

export const ACCESSIBILITY_RULES_BY_ID = Object.fromEntries(
  ACCESSIBILITY_RULES.map((rule) => [rule.id, rule])
);
