/**
 * WebXray - Security Rule Catalog (Defensive Audits Only)
 * Single source of truth for transport encryption and client header security.
 * Category weights sum to 100.
 */

export const SECURITY_RULES = [
  {
    id: 'sec-https',
    category: 'security',
    title: 'Website enforces encrypted HTTPS transport connection',
    description: 'Ensures data is transmitted over TLS/HTTPS rather than unencrypted HTTP.',
    weight: 25,
    severityOnFail: 'critical',
    whyItMatters: 'Unencrypted HTTP connections allow attackers on the same network to intercept, eavesdrop on, and manipulate transmitted data.',
    recommendation: 'Enable HTTPS on the web server with a valid SSL/TLS certificate and configure automatic 301 redirects from HTTP to HTTPS.',
    source: 'standard',
    reference: 'RFC 2818 (HTTP Over TLS)',
  },
  {
    id: 'sec-mixed-content',
    category: 'security',
    title: 'HTTPS page does not request insecure HTTP subresources',
    description: 'Verifies that scripts, stylesheets, and media are fetched exclusively over HTTPS.',
    weight: 15,
    severityOnFail: 'high',
    whyItMatters: 'Loading unencrypted HTTP resources inside an HTTPS page weakens SSL protections and triggers browser security warnings.',
    recommendation: 'Update all subresource URLs to use https:// or protocol-relative paths.',
    threshold: { maxInsecureResources: 0 },
    source: 'standard',
    reference: 'W3C Mixed Content Specification',
  },
  {
    id: 'sec-csp',
    category: 'security',
    title: 'Content-Security-Policy (CSP) header is defined',
    description: 'Validates that a CSP header restricts script execution and resource origins.',
    weight: 12,
    severityOnFail: 'high',
    whyItMatters: 'A robust CSP serves as a primary defense-in-depth barrier against Cross-Site Scripting (XSS) and code injection.',
    recommendation: 'Implement a Content-Security-Policy header specifying trusted script-src and object-src directives.',
    source: 'standard',
    reference: 'W3C Content Security Policy Level 3',
  },
  {
    id: 'sec-hsts',
    category: 'security',
    title: 'Strict-Transport-Security (HSTS) header is active',
    description: 'Ensures modern browsers remember to exclusively connect over HTTPS.',
    weight: 8,
    severityOnFail: 'medium',
    whyItMatters: 'Without HSTS, initial user requests can be intercepted or downgraded to insecure HTTP.',
    recommendation: 'Add Strict-Transport-Security: max-age=31536000; includeSubDomains.',
    source: 'standard',
    reference: 'RFC 6797 (HTTP Strict Transport Security)',
  },
  {
    id: 'sec-nosniff',
    category: 'security',
    title: 'X-Content-Type-Options: nosniff header is enabled',
    description: 'Prevents browsers from MIME-sniffing responses away from declared Content-Type.',
    weight: 6,
    severityOnFail: 'medium',
    whyItMatters: 'Allows browsers to MIME-sniff responses away from the declared content-type, potentially executing malicious scripts.',
    recommendation: 'Send X-Content-Type-Options: nosniff on all HTML and API responses.',
    source: 'standard',
    reference: 'Fetch Living Standard / MIME Sniffing Standard',
  },
  {
    id: 'sec-frame',
    category: 'security',
    title: 'Clickjacking defenses configured via frame-ancestors or X-Frame-Options',
    description: 'Ensures the page cannot be framed inside transparent malicious iframes.',
    weight: 6,
    severityOnFail: 'medium',
    whyItMatters: 'Without frame protections, malicious websites can embed this page in a transparent iframe to steal user interactions (clickjacking).',
    recommendation: 'Send X-Frame-Options: SAMEORIGIN or set CSP frame-ancestors "self".',
    source: 'standard',
    reference: 'RFC 7034 / CSP Level 3 frame-ancestors',
  },
  {
    id: 'sec-referrer',
    category: 'security',
    title: 'Referrer-Policy header restricts cross-origin URL leaks',
    description: 'Controls referrer data passed when navigating away from this site.',
    weight: 4,
    severityOnFail: 'low',
    whyItMatters: 'Full URLs including query parameters might leak to external domains upon navigation.',
    recommendation: 'Send Referrer-Policy: strict-origin-when-cross-origin.',
    source: 'standard',
    reference: 'W3C Referrer Policy Specification',
  },
  {
    id: 'sec-permissions',
    category: 'security',
    title: 'Permissions-Policy header restricts browser hardware APIs',
    description: 'Explicitly disables access to camera, microphone, and geolocation.',
    weight: 4,
    severityOnFail: 'low',
    whyItMatters: 'Leaves browser hardware feature access open to default policies without explicit scoping.',
    recommendation: 'Configure Permissions-Policy to explicitly restrict camera, microphone, and geolocation.',
    source: 'standard',
    reference: 'W3C Permissions Policy Specification',
  },
  {
    id: 'sec-tabnabbing',
    category: 'security',
    title: 'External target="_blank" links include rel="noopener" or rel="noreferrer"',
    description: 'Protects against reverse tabnabbing window.opener redirects.',
    weight: 10,
    severityOnFail: 'medium',
    whyItMatters: 'Opening links in new tabs without noopener gives the opened page access to window.opener, enabling reverse tabnabbing phishing redirects.',
    recommendation: 'Add rel="noopener noreferrer" to all anchor tags with target="_blank".',
    threshold: { maxVulnerable: 0 },
    source: 'standard',
    reference: 'HTML Living Standard (Link types: noopener)',
  },
  {
    id: 'sec-third-party',
    category: 'security',
    title: 'Third-party resource dependency surface is kept lean',
    description: 'Monitors the number of external origins loaded on the page.',
    weight: 10,
    severityOnFail: 'medium',
    whyItMatters: 'High dependency on third-party scripts expands the supply chain attack surface and exposes user activity to external entities.',
    recommendation: 'Audit third-party tags and analytics, self-host critical libraries, and enforce strict CSP.',
    threshold: { maxThirdParty: 25 },
    source: 'heuristic',
    reference: 'Web Security Supply Chain Reduction Guidelines',
  },
];

export const SECURITY_RULES_BY_ID = Object.fromEntries(
  SECURITY_RULES.map((rule) => [rule.id, rule])
);
