/**
 * WebXray - SEO Rule Catalog
 * Single source of truth for technical and on-page SEO audits.
 * Category weights sum to 100.
 */

export const SEO_RULES = [
  {
    id: 'seo-title-length',
    category: 'seo',
    title: 'Page title is between 30 and 60 characters',
    description: 'Ensures the document title is descriptive and will not be truncated in search results.',
    weight: 20,
    severityOnFail: 'critical',
    whyItMatters: 'The page title is the single most critical on-page SEO signal. Search engines use it as the primary headline in search result pages.',
    recommendation: 'Add a descriptive <title> tag between 30 and 60 characters containing primary keywords.',
    threshold: { min: 30, max: 60, unit: 'characters' },
    source: 'heuristic',
    reference: 'Google Search Central Title Link Guidelines',
  },
  {
    id: 'seo-meta-description',
    category: 'seo',
    title: 'Meta description is between 70 and 160 characters',
    description: 'Verifies the presence and length of the meta description snippet.',
    weight: 15,
    severityOnFail: 'high',
    whyItMatters: 'Without a meta description, search engines auto-generate snippet text from random page copy, often resulting in lower click-through rates (CTR).',
    recommendation: 'Add an informative meta description between 70 and 160 characters summarizing the page and including a call to action.',
    threshold: { min: 70, max: 160, unit: 'characters' },
    source: 'heuristic',
    reference: 'Google Search Central Meta Description Snippet Guidelines',
  },
  {
    id: 'seo-h1',
    category: 'seo',
    title: 'Document contains exactly one H1 heading',
    description: 'Checks for a single prominent primary heading that establishes page topic.',
    weight: 15,
    severityOnFail: 'high',
    whyItMatters: 'An H1 heading represents the primary subject of the page for search indexers and assistive technologies.',
    recommendation: 'Add exactly one <h1> heading near the top of the page reflecting the primary page topic.',
    threshold: { target: 1 },
    source: 'heuristic',
    reference: 'HTML5 Semantic Heading Structure',
  },
  {
    id: 'seo-heading-hierarchy',
    category: 'seo',
    title: 'Headings follow a logical sequential order without skips',
    description: 'Checks that heading levels progress sequentially without jumping levels (e.g., H2 to H4).',
    weight: 10,
    severityOnFail: 'medium',
    whyItMatters: 'Skipping heading levels (such as H2 directly to H4) confuses screen readers and breaks logical document structuring for search bots.',
    recommendation: 'Organize headings in strictly descending sequential order (H1 → H2 → H3).',
    threshold: { maxSkips: 0 },
    source: 'heuristic',
    reference: 'W3C Headings and Document Outline Guidelines',
  },
  {
    id: 'seo-canonical',
    category: 'seo',
    title: 'Authoritative canonical URL is declared',
    description: 'Ensures a rel="canonical" link tag specifies the authoritative page URL.',
    weight: 10,
    severityOnFail: 'medium',
    whyItMatters: 'Canonical URLs prevent duplicate content issues when pages are accessed via multiple URL parameters or protocols.',
    recommendation: 'Add a <link rel="canonical" href="..."> pointing to the authoritative URL of this page.',
    source: 'standard',
    reference: 'RFC 6596 (The Canonical Link Relation)',
  },
  {
    id: 'seo-robots',
    category: 'seo',
    title: 'Robots meta tag permits public indexing',
    description: 'Validates that robots meta tags do not accidentally block search engines with noindex.',
    weight: 10,
    severityOnFail: 'high',
    whyItMatters: 'The "noindex" directive instructs search engines not to index or display this page in public search results.',
    recommendation: 'If this page is intended for organic search traffic, remove the "noindex" attribute immediately.',
    source: 'standard',
    reference: 'Robots Exclusion Protocol / RFC 9309',
  },
  {
    id: 'seo-social-metadata',
    category: 'seo',
    title: 'Open Graph and Twitter social card tags are defined',
    description: 'Checks for og:title, og:description, og:image, and twitter:card meta tags.',
    weight: 8,
    severityOnFail: 'medium',
    whyItMatters: 'Without Open Graph and Twitter Card tags, shares on LinkedIn, Facebook, Slack, and X lack rich thumbnails and descriptions.',
    recommendation: 'Add og:title, og:description, og:image, and twitter:card meta tags.',
    source: 'standard',
    reference: 'Open Graph Protocol Specification',
  },
  {
    id: 'seo-image-alt',
    category: 'seo',
    title: 'All images declare descriptive alternative text',
    description: 'Audits image tags for alt attributes that inform search crawlers of image contents.',
    weight: 4,
    severityOnFail: 'high',
    whyItMatters: 'Search engines index image alt text for image search ranking, and screen readers require alt text for accessibility.',
    recommendation: 'Add descriptive alt text to informative images, or alt="" to purely decorative graphics.',
    threshold: { maxMissing: 0 },
    source: 'standard',
    reference: 'WCAG 1.1.1 Non-text Content',
  },
  {
    id: 'seo-link-anchors',
    category: 'seo',
    title: 'Links use descriptive keyword anchor text',
    description: 'Flags generic anchor text such as "click here" or "read more".',
    weight: 4,
    severityOnFail: 'medium',
    whyItMatters: 'Generic link anchor text ("click here", "read more") provides poor context to search engines about the destination page.',
    recommendation: 'Replace generic text with keyword-rich descriptive anchors explaining where the link leads.',
    threshold: { maxNonDescriptive: 0 },
    source: 'heuristic',
    reference: 'Google Search Central Link Best Practices',
  },
  {
    id: 'seo-html-lang',
    category: 'seo',
    title: 'HTML root element declares language attribute',
    description: 'Confirms <html lang="..."> attribute is present for regional and language targeting.',
    weight: 4,
    severityOnFail: 'medium',
    whyItMatters: 'Declaring language assists search engines in geographic and language-specific search ranking and allows screen readers to use correct phonetics.',
    recommendation: 'Add a lang attribute to the <html> tag (e.g. <html lang="en">).',
    source: 'standard',
    reference: 'W3C Internationalization / BCP 47',
  },
];

export const SEO_RULES_BY_ID = Object.fromEntries(
  SEO_RULES.map((rule) => [rule.id, rule])
);
