/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './popup.html',
    './sidepanel.html',
    './src/**/*.{js,jsx}',
  ],
  darkMode: 'class',
  theme: {
    borderRadius: {
      none: '0',
      sm: '4px',
      DEFAULT: '6px',
      md: '6px',
      lg: '6px',
      xl: '6px',
      '2xl': '6px',
      full: '9999px',
      chip: '4px',
      control: '6px',
    },
    boxShadow: {
      none: 'none',
      DEFAULT: 'none',
      sm: 'none',
      md: 'none',
      lg: 'none',
      xl: 'none',
      '2xl': 'none',
    },
    extend: {
      fontFamily: {
        sans: ['-apple-system', '"Segoe UI"', 'system-ui', 'sans-serif'],
        mono: ['ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', '"Liberation Mono"', '"Courier New"', 'monospace'],
      },
      fontSize: {
        caption: ['11px', { lineHeight: '15px' }],
        ui: ['12px', { lineHeight: '16px' }],
        primary: ['13px', { lineHeight: '18px' }],
        section: ['16px', { lineHeight: '22px' }],
        page: ['20px', { lineHeight: '26px' }],
        score: ['28px', { lineHeight: '32px' }],
        // Safe mappings for existing classes during transition
        xs: ['12px', { lineHeight: '16px' }],
        sm: ['13px', { lineHeight: '18px' }],
        base: ['12px', { lineHeight: '16px' }],
        lg: ['16px', { lineHeight: '22px' }],
        xl: ['20px', { lineHeight: '26px' }],
        '2xl': ['28px', { lineHeight: '32px' }],
      },
      colors: {
        wl: {
          bg: 'var(--wl-bg)',
          surface: 'var(--wl-surface)',
          raised: 'var(--wl-raised)',
          border: 'var(--wl-border)',
          text: 'var(--wl-text)',
          muted: 'var(--wl-muted)',
          accent: 'var(--wl-accent)',
          'accent-hover': 'var(--wl-accent-hover)',
          'accent-muted': 'var(--wl-accent-muted)',
          critical: 'var(--wl-critical)',
          'critical-bg': 'var(--wl-critical-bg)',
          'critical-border': 'var(--wl-critical-border)',
          high: 'var(--wl-high)',
          'high-bg': 'var(--wl-high-bg)',
          'high-border': 'var(--wl-high-border)',
          medium: 'var(--wl-medium)',
          'medium-bg': 'var(--wl-medium-bg)',
          'medium-border': 'var(--wl-medium-border)',
          low: 'var(--wl-low)',
          'low-bg': 'var(--wl-low-bg)',
          'low-border': 'var(--wl-low-border)',
          passed: 'var(--wl-passed)',
          'passed-bg': 'var(--wl-passed-bg)',
          'passed-border': 'var(--wl-passed-border)',
        },
        brand: {
          bg: '#0e1116',
          surface: '#151a21',
          raised: '#1b212a',
          border: '#262d38',
          text: '#e6e9ee',
          muted: '#8b94a3',
          accent: '#4f8cff',
        },
        // Temporary aliases to prevent build breakages on existing components
        dark: {
          950: '#0e1116',
          900: '#151a21',
          850: '#1b212a',
          800: '#262d38',
          750: '#262d38',
          700: '#334155',
        },
      },
      transitionDuration: {
        DEFAULT: '120ms',
        fast: '120ms',
      },
    },
  },
  plugins: [],
};
